
## Setup

```{r}
library(tidyverse)  # read_csv and mutate
library(lme4)       # lmer
library(emmeans)    # emmeans and pairs
library(lmerTest)
library(ordinal)
library(performance)
library(modelsummary)
library(lmerTest)

df_long4 <- read_csv('/Users/sm6511/Desktop/Prediction-Accomodation-Exp/data/Combined/df_long_for_R-Study1.csv') |>
  mutate(
    task = relevel(factor(task), ref = "predict"),
    feature_relevance = relevel(factor(feature_relevance), ref = "irrelevant"),
    feature_dimension = relevel(factor(feature_dimension), ref = "color"),
  )
```

```{r}
#| fig-width: 14
#| fig-height: 10
contrasts(df_long4$task) <- contr.sum(2)
contrasts(df_long4$feature_relevance) <- contr.sum(2)
contrasts(df_long4$feature_dimension) <- contr.sum(3)

model_eff <- lmer(
  feature_importance ~ task * feature_relevance *
    feature_dimension +
    (1|participant),
  data = df_long4
)
summary(model_eff)
```
```{r}
emm <- emmeans(
  model_eff,
  ~ task * feature_relevance * feature_dimension
)

emm
pairs(
  emm,
  by = c("feature_relevance", "feature_dimension")
)
```


```{r}
library(tidyverse)

plot_df <- df_long4 %>%
  group_by(task, feature_relevance, feature_dimension) %>%
  summarise(
    mean = mean(feature_importance, na.rm = TRUE),
    se = sd(feature_importance, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )

ggplot(
  plot_df,
  aes(
    x = feature_dimension,
    y = mean,
    color = task,
    group = task
  )
) +
  geom_point(
    position = position_dodge(width = .3),
    size = 3
  ) +
  geom_line(
    position = position_dodge(width = .3)
  ) +
  geom_errorbar(
    aes(
      ymin = mean - se,
      ymax = mean + se
    ),
    width = .15,
    position = position_dodge(width = .3)
  ) +
  facet_wrap(~ feature_relevance) +
  theme_classic() +
  labs(
    x = "Feature Dimension",
    y = "Mean Feature Importance",
    color = "Task"
  )
```

```{r}
emm <- emmeans(
  model_eff,
  ~ task * feature_relevance * feature_dimension
)

emm
pairs(
  emm,
  by = c("feature_relevance", "feature_dimension")
)
```


```{r}
library(car)

Anova(model_eff, type = 3)
```



```{r}
df_long4_ord <- df_long4 |>
  mutate(
    abs_feature_importance = abs(feature_importance),
    abs_feature_importance_ord = ordered(abs_feature_importance)
  )

contrasts(df_long4_ord$task) <- contr.sum(2)
contrasts(df_long4_ord$feature_dimension) <- contr.sum(3)
contrasts(df_long4_ord$feature_relevance) <- contr.sum(2)

model_clmm_abs <- clmm(
  abs_feature_importance_ord ~
    task * feature_dimension * feature_relevance +
    (1 | participant),
  data = df_long4_ord,
  link = "logit"
)
```

```{r}
summary(model_clmm_abs)
```


```{r}
df_corr <- read_csv('/Users/sm6511/Desktop/Prediction-Accomodation-Exp/data/Combined/df_corr_for_R_Study1.csv') |>
  mutate(
    task = factor(task),
    feature_relevance = factor(feature_relevance),
    feature_dimension = factor(feature_dimension)
  )

# Effect / sum coding
contrasts(df_corr$task) <- contr.sum(2)
contrasts(df_corr$feature_relevance) <- contr.sum(2)
contrasts(df_corr$feature_dimension) <- contr.sum(3)

model_corr_raw_eff <- lmer(
  correlation ~ task * feature_relevance * feature_dimension +
    (1 | participant),
  data = df_corr
)

summary(model_corr_raw_eff)
```
```{r}

emm <- emmeans(
  model_corr_raw_eff,
  ~ task * feature_relevance * feature_dimension
)

emm
pairs(
  emm,
  by = c("feature_relevance", "feature_dimension")
)
```


```{r}
library(tidyverse)

plot_df <- df_corr %>%
  group_by(task, feature_relevance, feature_dimension) %>%
  summarise(
    mean = mean(correlation, na.rm = TRUE),
    se = sd(correlation, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )

ggplot(
  plot_df,
  aes(
    x = feature_dimension,
    y = mean,
    color = task,
    group = task
  )
) +
  geom_point(
    position = position_dodge(width = .3),
    size = 3
  ) +
  geom_line(
    position = position_dodge(width = .3)
  ) +
  geom_errorbar(
    aes(
      ymin = mean - se,
      ymax = mean + se
    ),
    width = .15,
    position = position_dodge(width = .3)
  ) +
  facet_wrap(~ feature_relevance) +
  theme_classic() +
  labs(
    x = "Feature Dimension",
    y = "Mean Correlation",
    color = "Task"
  )
```


```{r}
df_merged <- read_csv('/Users/sm6511/Desktop/Prediction-Accomodation-Exp/data/Combined/df_merged_for_R_Study1.csv') |>
  mutate(
    task = relevel(factor(task), ref = "predict"),

    color_relevance = ifelse(irrelevant_dim == "color", "irrelevant", "relevant"),
    tail_relevance  = ifelse(irrelevant_dim == "tail",  "irrelevant", "relevant"),
    shape_relevance  = ifelse(irrelevant_dim == "shape",  "irrelevant", "relevant"),

    color_match_high = ifelse(color == color_high, 1, 0),
    tail_match_high  = ifelse(tail  == tail_high,  1, 0),
    shape_match_high  = ifelse(shape  == shape_high,  1, 0)
  )
```

```{r}
df_cue <- df_merged |>
  pivot_longer(
    cols = c(color_match_high, tail_match_high, shape_match_high),
    names_to = "feature_dimension",
    values_to = "match_high"
  ) |>
  mutate(
    feature_dimension = str_remove(feature_dimension, "_match_high"),
    feature_relevance = case_when(
      feature_dimension == "color" ~ color_relevance,
      feature_dimension == "tail"  ~ tail_relevance,
      feature_dimension == "shape"  ~ shape_relevance
    )
  ) |>
  group_by(
    task, conditionOrder,
    relevant_dim_1, relevant_dim_2, irrelevant_dim,
    feature_dimension, feature_relevance
  ) |>
  summarise(
    pred = mean(testing_responses[match_high == 1], na.rm = TRUE) -
           mean(testing_responses[match_high == 0], na.rm = TRUE),

    true = mean(food_amount[match_high == 1], na.rm = TRUE) -
           mean(food_amount[match_high == 0], na.rm = TRUE),

    .groups = "drop"
  ) |>
  mutate(
    signed_error = pred - true,
    abs_error = abs(pred - true),

    task = relevel(factor(task), ref = "predict"),
    feature_dimension = relevel(factor(feature_dimension), ref = "tail"),
    feature_relevance = relevel(factor(feature_relevance), ref = "irrelevant")
  )
```

```{r}

contrasts(df_cue$task) <- contr.sum(2)
contrasts(df_cue$feature_relevance) <- contr.sum(2)
contrasts(df_cue$feature_dimension) <- contr.sum(3)

model_signed <- lmer(
  signed_error ~ task * feature_relevance * feature_dimension +
    (1 | conditionOrder),
  data = df_cue
)

summary(model_signed)
```

```{r}
emm <- emmeans(
  model_signed,
  ~ task * feature_relevance * feature_dimension
)

emm
pairs(
  emm,
  by = c("feature_relevance", "feature_dimension")
)
```

```{r}
library(ggplot2)

ggplot(
  df_cue,
  aes(
    x = feature_dimension,
    y = signed_error,
    color = task,
    group = task
  )
) +
  stat_summary(
    fun = mean,
    geom = "point",
    position = position_dodge(width = .2),
    size = 3
  ) +
  stat_summary(
    fun = mean,
    geom = "line",
    position = position_dodge(width = .2)
  ) +
  stat_summary(
    fun.data = mean_se,
    geom = "errorbar",
    width = .1,
    position = position_dodge(width = .2)
  ) +
  facet_wrap(~feature_relevance) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    x = "Feature",
    y = "Error (Participant effect − True effect)",
    color = "Task"
  ) +
  theme_classic()
```


