
## Setup

```{r}
library(tidyverse)  # read_csv and mutate
library(lme4)       # lmer
library(emmeans)    # emmeans and pairs
library(lmerTest)
library(ordinal)
library(performance)
library(modelsummary)
library(lmerTest)

df_params <- read_csv('/Users/sm6511/Desktop/Prediction-Accomodation-Exp/data/Combined/df_params_study4_for_r.csv')

df_params <- df_params %>%
  mutate(
    overfit = as.integer(overfit),
    task = factor(
      task,
      levels = c("predict", "accommodate")
    ),
    irrelevant_dim = factor(
      irrelevant_dim,
      levels = c("feet", "stripes")
    )
  )
```

```{r}
contrasts(df_params$task)              <- contr.sum(2)
contrasts(df_params$irrelevant_dim) <- contr.sum(2)
model_overfit <- glm(
  overfit ~ task * irrelevant_dim,
  data = df_params,
  family = binomial(link = "logit")
)

summary(model_overfit)
drop1(model_overfit, test = "Chisq")
```
```{r}
df_long4 <- read_csv('/Users/sm6511/Desktop/Prediction-Accomodation-Exp/data/Combined/df_long_for_R-Study4.csv') |>
  mutate(
    task = relevel(factor(task), ref = "accommodate"),
    feature_relevance = relevel(factor(feature_relevance), ref = "relevant"),
    feature_dimension = relevel(factor(feature_dimension), ref = "feet")
  )
```

```{r}
contrasts(df_long4$task) <- contr.sum(2)
contrasts(df_long4$feature_relevance) <- contr.sum(2)
contrasts(df_long4$feature_dimension) <- contr.sum(2)

model_eff <- lmer(
  feature_importance ~ task * feature_relevance *
    feature_dimension +
    (1|participant),
  data = df_long4
)
summary(model_eff)
```
```{r}
emm <- emmeans(
  model_eff,
  ~ task * feature_relevance * feature_dimension
)

emm
pairs(
  emm,
  by = c("feature_relevance", "feature_dimension")
)
```

```{r}
model_eff <- lmer(
  abs_feature_importance ~ task * feature_relevance *
    feature_dimension +
    (1|participant),
  data = df_long4
)
summary(model_eff)
```

```{r}
df_merged <- read_csv('/Users/sm6511/Desktop/Prediction-Accomodation-Exp/data/Combined/df_merged_for_R-Study4.csv') |>
  mutate(
    task = relevel(factor(task), ref = "predict"),
    stripes_relevance = ifelse(irrelevant_dim == "stripes", "irrelevant", "relevant"),
    feet_relevance  = ifelse(irrelevant_dim == "feet", "irrelevant", "relevant"),
    stripes_match_high = ifelse(stripes == stripes_high, 1, 0),
    feet_match_high  = ifelse(feet == feet_high, 1, 0),
    participant = interaction(task, conditionOrder, drop = TRUE)
  )
```

```{r}
df_cue <- df_merged |>
  pivot_longer(
    cols = c(
      stripes_match_high,
      feet_match_high
    ),
    names_to = "feature_dimension",
    values_to = "match_high"
  ) |>
  mutate(
    feature_dimension = str_remove(
      feature_dimension,
      "_match_high"
    ),

    feature_relevance = case_when(
      feature_dimension == "stripes" ~ stripes_relevance,
      feature_dimension == "feet"    ~ feet_relevance,
      TRUE ~ NA_character_
    )
  ) |>
  group_by(
    participant,
    task,
    conditionOrder,
    relevant_dim,
    irrelevant_dim,
    feature_dimension,
    feature_relevance
  ) |>
  summarise(
    # Participant's estimated effect of this feature
    pred = mean(
      testing_responses[match_high == 1],
      na.rm = TRUE
    ) -
      mean(
        testing_responses[match_high == 0],
        na.rm = TRUE
      ),

    # True effect of this feature in the training data
    true = mean(
      fertility_score[match_high == 1],
      na.rm = TRUE
    ) -
      mean(
        fertility_score[match_high == 0],
        na.rm = TRUE
      ),

    .groups = "drop"
  ) |>
  mutate(
    signed_error = pred - true,
    abs_error = abs(signed_error),

    
    task = relevel(
      factor(
        task,
        levels = c("predict", "accommodate")
      ),
      ref = "predict"
    ),

    feature_dimension = factor(
      feature_dimension,
      levels = c("stripes", "feet"),
      labels = c("Stripes", "Feet")
    ),

    feature_relevance = relevel(
      factor(
        feature_relevance,
        levels = c("irrelevant", "relevant")
      ),
      ref = "irrelevant"
    )
  )
```

```{r}
contrasts(df_cue$task) <- contr.sum(2)
contrasts(df_cue$feature_relevance) <- contr.sum(2)
contrasts(df_cue$feature_dimension) <- contr.sum(2)

model_cue_raw_eff <- lmer(
  abs_error ~ task * feature_relevance * feature_dimension + (1|participant),
  data = df_cue
)

summary(model_cue_raw_eff)
```

```{r}
emmeans(model_cue_raw_eff,
         ~ feature_relevance * feature_dimension)
```

```{r}
df_corr <- read_csv('/Users/sm6511/Desktop/Prediction-Accomodation-Exp/data/Combined/df_corr_for_R_Study4.csv') |>
  mutate(
    task = factor(task),
    feature_relevance = factor(feature_relevance),
    feature_dimension = factor(feature_dimension)
  )
contrasts(df_corr$task) <- contr.sum(2)
contrasts(df_corr$feature_relevance) <- contr.sum(2)
contrasts(df_corr$feature_dimension) <- contr.sum(2)

model_corr_raw_eff <- lmer(
  correlation ~ task * feature_relevance * feature_dimension + (1|participant),
  data = df_corr
)

summary(model_corr_raw_eff)
```

```{r}
model_corr_raw_eff <- lmer(
  abs_correlation ~ task * feature_relevance * feature_dimension + (1|participant),
  data = df_corr
)

summary(model_corr_raw_eff)
```

#Looking at associations between actual correlation of feature with food amount in training (supplement in preregistration)
```{r}
df_irrelevant <- subset(df_corr,
                        feature_relevance == "irrelevant")

model <- lm(
    correlation ~ task * actual_correlation,
    data = df_irrelevant
)
summary(model)
```

```{r}
library(ggplot2)

ggplot(
  df_irrelevant,
  aes(
    x = actual_correlation,
    y = correlation,
    color = task
  )
) +
  geom_point(
    alpha = 0.7,
    size = 2.5
  ) +
  geom_smooth(
    method = "lm",
    se = TRUE
  ) +
  labs(
    x = "Actual correlation during training",
    y = "Participant correlation during test",
    color = "Task"
  ) +
  theme_classic(base_size = 14)
```
